# Generated by Django 5.2.8 on 2026-03-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_contact_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='published_date',
        ),
    ]
